name: Recipes with Angular.js
pygments: true
table_of_contents:
  dirs: [introduction, controllers]
assets:
  compress:
    js:   uglifier
    css:  sass
  baseurl: http://fdietz.github.io/recipes-with-angular-js/assets/